### ISSUE TITLE
Migrate pr2_kinematics to github

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_kinematics#1]
Currently at: https://code.ros.org/svn/wg-ros-pkg/stacks/pr2_kinematics/trunk

Also migrate issues.

**Comment by airballking** [comment]
Migrated to git with history: https://github.com/airballking/pr2_kinematics

@ahendrix : Where do I find the original issues?

**Comment by trainman419** [comment]
Don't even bother trying to ressurect the issue history.

**Comment by airballking** [comment]
Alright.

**Comment by trainman419** [comment]
Imported. I've also given you commit access to pr2_kinematics.

**Comment by airballking** [comment]
Thanks.
