### ISSUE TITLE
Release into ROS Jade

### ISSUE THREAD

**Issue by 130s** [PR2/pr2_kinematics#6]
I'm making a release for `moveit_pr2` (which is required by https://github.com/ros-planning/moveit_metapackages/issues/6) and it requires this pkg. Thank you for taking time.

**Comment by v4hn** [comment]
Let me add that moveit_pr2 contains the traditional MoveIt! tutorials in pr2_moveit_tutorials.
So dropping the repo and the dependency to this package here is not an option for now.

@TheDash I know you're way to busy with pr2 indigo-upgrade support & otto, and I also know this
is not particularly relevant for actual PR2 users (I'm rather sure, nobody will use jade there), but it is
important for MoveIt to have working tutorials around!
Do you think you could therefore release this module into jade? Everything else seems to be in place..

**Comment by v4hn** [comment]
I think in the long run (kinetic) it is probably a good idea to get rid of this module altogether and
switch to trac or at least a more generic plugin for the pr2. But this will need a rather detailed understanding of the code...
